language: go

os:
  - linux
  - osx

go:
  - 1.5.1

env:
  - TARGETS="check full-coverage"
  - TARGETS="crosscompile"

# Only execute the crosscompile target one time during the build.
matrix:
  exclude:
    - os: osx
      env: TARGETS="crosscompile"

sudo: false

addons:
  apt:
    packages:
      - python-virtualenv
      - geoip-database

before_install:
  # Redo the travis setup but with the elastic/filebeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/elastic/filebeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/elastic/filebeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/elastic/filebeat
  - cd $HOME/gopath/src/github.com/elastic/filebeat

install:
  - make

script:
  - make $TARGETS

notifications:
  hipchat:
    rooms:
      secure: AvDY1qPSt+eeZk6AtOlaQMHqJnRc9wL8NtMT2NoXvCc0yAewOeeSAjIDhlm/+kMisV9o56pBLD3TWSi9IC4fesEucGkKsQ3JDTwEhWFCeVN8njnmzCZ3wSlg2WvdkfFhrjpY4kxYIlJw+Mp4T/ZW87EqcNwbOfSm1/cXQdAa8IqZ2bwdyfvgLugEI0OTg2qvA4N/J/wx1sUyM4/PP9LKGAeerlwuWLOSHaX5AEqyzLEUuKapHK92cyBPqtzFpi8+kFnKhIMMbPqmcSV5wdxHKWEALOLBbaNTiuC4TWkdNm1fEKqns/rU60Z4AhyLjbeRHsdqc50urwbNwMfOc96BvoQV3gxOfBD2nmkmm0FKiRyMVB71KLXSG3tkOoEu7bUDxWHAucDC+3F4cDwRF3sSGxX1EwneceV6jdt+V0U+gFXHo4CoC/riYFiTR4I1QA94/K5paKBxICdN+/ooscqqhI80YztmyaOtkbWROXd0Of5+jHdb11uOjgsCgJUNXN3ve5Z9RYJTQxwRRKtKGj7HEWKUOr9GwGbCg81V4IxGHYwWW+vwX7XjXzwoDK6hI4sf9fz+Mc4VGtPeGl8zZ6mjxsKn1UPI94Mb2tAShA3LRas6O4MFS+ANHFnxa4vTU7lGcXNdaQU6Xveqk4Y6XbvP6Ag+woQF3ThyzBObT4Pw2nM=

after_success:
  # Copy profile.cov to coverage.txt because codecov.io requires this file
  - test -f coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f coverage/full.cov
